= Building Block View
:description: Overview of source code and components by making its structure understandable through abstraction.

{description}

== Overview
[plantuml, puml-build-image, svg]
----
@startuml

skinparam linetype ortho
skinparam monochrome false
skinparam componentStyle uml2
skinparam backgroundColor transparent
skinparam ArrowColor #212121
skinparam NoteBorderColor #212121
skinparam NoteFontColor #212121
skinparam NoteBackgroundColor #fff
skinparam ComponentBorderColor #212121
skinparam ComponentFontColor #212121
skinparam DatabaseBorderColor #212121
skinparam DatabaseFontColor #212121
skinparam FileBorderColor #212121
skinparam FileFontColor #212121
skinparam ControlBorderColor #212121
skinparam ControlFontColor #212121
skinparam RectangleBackgroundColor transparent
skinparam RectangleBorderColor #212121
skinparam RectangleFontColor #212121
skinparam ControlBackgroundColor transparent
skinparam ControlBorderColor #212121
skinparam ControlFontColor #212121
skinparam HexagonBackgroundColor transparent
skinparam HexagonBorderColor #212121
skinparam HexagonFontColor #212121
skinparam ArtifactBorderColor #212121
skinparam ArtifactFontColor #212121
skinparam defaultTextAlignment center
skinparam activity {
    'FontName Ubuntu
    FontName Roboto
}

rectangle github as "Github.com" {
    database repo as "Website\nRepo" <<Github>>
    component ui_bundle as "UI\nBundle" <<Sources>>
    collections adoc as "Asciidoc\nContents" <<Sources>>

    ui_bundle -up-> repo
    adoc -up-> repo

    queue build_workflow <<Github Actions>>
    repo -right-> build_workflow
}

rectangle dockerhub as "hub.docker.com" {
    artifact image as "Website\nContainer\nImage" <<Docker>>
}

build_workflow -right-> image

artifact kroki as "Kroki.io"

build_workflow -up-> kroki
kroki -down-> build_workflow

@enduml
----

== Developing inside a Container
The link:https://code.visualstudio.com/docs/devcontainers/containers[Visual Studio Code Dev Containers extension] lets you use a container as a full-featured development environment. It allows you to open any folder inside (or mounted into) a container and take advantage of Visual Studio Code's full feature set. A link:https://code.visualstudio.com/docs/devcontainers/containers#_create-a-devcontainerjson-file[devcontainer.json] file in your project tells VS Code how to access (or create) a development container with a well-defined tool and runtime stack. This container can be used to run an application or to separate tools, libraries, or runtimes needed for working with a codebase.

Workspace files are mounted from the local file system or copied or cloned into the container. Extensions are installed and run inside the container, where they have full access to the tools, platform, and file system.

This project is equipped with a convenient devcontainer that houses all the necessary dependencies to effortlessly construct and operate a website using Antora. This setup simplifies the development process by ensuring that everything essential for building and running the website is readily available within the container.

Furthermore, the devcontainer configuration initiates a Portainer instance specifically on port 7990. Portainer serves as a management tool for Docker containers, and by exposing it to the host on this particular port, it allows for easy access and administration of the containers within the environment. This exposed Portainer instance simplifies the monitoring and handling of containers used in the development process.

== Antora
This website is constructed using Antora, and all its pages originate from Asciidoc files.

link:https://antora.org[Antora] is a static site generator that simplifies the process of creating documentation websites. It takes content from link:https://docs.asciidoctor.org/asciidoc/latest[Asciidoc] files, which are simple text documents formatted with a lightweight markup language, and turns them into a cohesive website.

These Asciidoc files aren't stored in a single place but rather exist across different repositories. All these repositories are part of the sommerfeld-io GitHub organization. That means that every repository can carry its own documentation. Antora is the tool that brings all this content together, formats it into a cohesive structure, and presents it as a unified documentation website for easy access and navigation.

This website uses link:https://kroki.io[Kroki] to generate diagrams from text sources. PlantUML is mostly used with this website, although other diagram types are supported as well.
