= Cross-cutting Concepts
:description: Overall, principal regulations and solution ideas that are relevant in multiple parts (= cross-cutting) of the system.

{description}
In many ways, this repository acts as a blueprint for other projects in the link:https://github.com/sommerfeld-io[Sommerfeld.io Github organization].

== Github Organization Settings
The link:https://github.com/sommerfeld-io[Sommerfeld.io Github organization] is structured to consolidate multiple projects under a single umbrella. This bundling approach  allows for easier management, collaboration, and resource-sharing among the various projects it encompasses. By centralizing these projects, it streamlines administrative tasks, fosters synergies among contributors, and provides a cohesive platform for developers interested in these specific projects.

link:https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations[Organizations] are shared accounts where businesses and open-source projects can collaborate across many projects at once, with sophisticated security and administrative features.

You can invite an unlimited number of people to join your organization, In addition to managing access to the organization itself, you can separately manage access to your organization's repositories, project boards, and apps. To harden your organization's security, you can enforce security requirements and review the organization's audit log. All organizations can own an unlimited number of public and private repositories.

=== Discussions
Setting up Discussions for your organization will allow you to broadcast updates, answer questions, and hold conversations for the entire organization.

Discussions cannot be enabled / disabled for each individual repository. Discussions are enabled for all repositories at organization-level (see https://github.com/organizations/sommerfeld-io/settings/discussions).

=== Actions secrets
Create link:https://github.com/organizations/sommerfeld-io/settings/secrets/actions[Github Actions secrets for the organization] to prepare interaction with DockerHub and Google Chat from Github Actions workflows:

[cols="1,3", options="header"]
|===
|Secrets |Description
|`DOCKERHUB_USER` |Bitwarden entry "DOCKERHUB_USER"
|`DOCKERHUB_TOKEN` |See https://hub.docker.com/settings/security (Access Token Description = "Github Organization sommerfeld-io")
|`GH_TOKEN_REPO_AND_PROJECT` |Bitwarden entry "GH_TOKEN_REPO_AND_PROJECT"
|`GOOGLE_CHAT_WEBHOOK` |Google Chat (Account = sebastian@sommerfeld.io) -> Channel "Workflows: sommerfeld-io" -> Apps & Integrations -> Manage Webhooks
|===

=== Dependabot secrets
Create link:https://github.com/organizations/sommerfeld-io/settings/secrets/dependabot[Dependabot secrets for the organization] to allow successful Github Actions workflows which are triggered by dependabot (like assigning PRs to a project).

[cols="1,3", options="header"]
|===
|Secrets |Description
|`DOCKERHUB_USER` |Bitwarden entry "DOCKERHUB_USER"
|`DOCKERHUB_TOKEN` |See https://hub.docker.com/settings/security (Access Token Description = "Github Organization sommerfeld-io")
|`GH_TOKEN_REPO_AND_PROJECT` |Bitwarden entry "GH_TOKEN_REPO_AND_PROJECT"
|`GOOGLE_CHAT_WEBHOOK` |Google Chat (Account = sebastian@sommerfeld.io) -> Channel "Workflows: sommerfeld-io" -> Apps & Integrations -> Webhooks
|===

== Github Repository Settings
A summary of all settings that are specific to this project.

=== Actions Secrets
Create link:https://github.com/organizations/sommerfeld-io/settings/secrets/actions[Github Actions secrets for the organization] to prepare interaction with DockerHub and Google Chat from Github Actions workflows:

[cols="1,3", options="header"]
|===
|Secrets |Description
|`DOCKERHUB_USER` |My DockerHub User
|`DOCKERHUB_TOKEN` |See https://hub.docker.com/settings/security (Access Token Description = "Repo www-sommerfeld-io")
|`GH_TOKEN_REPO_AND_PROJECT` |Bitwarden entry "GH_TOKEN_REPO_AND_PROJECT"
|`GOOGLE_CHAT_WEBHOOK` |Google Chat (Account = sebastian@sommerfeld.io) -> Channel "Workflows: sommerfeld-io" -> Apps & Integrations -> Manage Webhooks
|===

NOTE: Secrets must be specified here because a private repository cannot inherit actions secrets from the organization with my plan.

=== Dependabot Secrets
Create link:https://github.com/organizations/sommerfeld-io/settings/secrets/dependabot[Dependabot secrets for the organization] to allow successful Github Actions workflows which are triggered by dependabot (like assigning PRs to a project).

[cols="1,3", options="header"]
|===
|Secrets |Description
|`DOCKERHUB_USER` |Bitwarden entry "DOCKERHUB_USER"
|`DOCKERHUB_TOKEN` |See https://hub.docker.com/settings/security (Access Token Description = "Repo www-sommerfeld-io")
|`GH_TOKEN_REPO_AND_PROJECT` |Bitwarden entry "GH_TOKEN_REPO_AND_PROJECT"
|`GOOGLE_CHAT_WEBHOOK` |Google Chat (Account = sebastian@sommerfeld.io) -> Channel "Workflows: sommerfeld-io" -> Apps & Integrations -> Webhooks
|`SONAR_TOKEN` |Configured when creating the project in SonarCloud (manage Tokens on the link:https://sonarcloud.io/account/security[SonarCloud Security
|===

NOTE: Although dependabot secrets can be inherited from the organization with my plan, these would contain other values than the Actions secrets.

== Configuring the default `GITHUB_TOKEN` permissions
By default, when you create a new repository in your personal account, `GITHUB_TOKEN` only has read access for the `contents` and `packages` scopes. If you create a new repository in an organization, the setting is inherited from what is configured in the organization settings.

. On GitHub.com, navigate to the main page of the repository.
. Under your repository name, click *Settings*. If you cannot see the "Settings" tab, select the dropdown menu, then click *Settings*.
. In the left sidebar, click *Actions*, then click *General*.
. Under "Workflow permissions", choose whether you want the `GITHUB_TOKEN` to have read and write access for all scopes, or just read access for the `contents` and `packages` scopes.
.. For the sommerfeld-io organization choose *Read repository contents and packages permissions*.
.. For the sommerfeld-io organization check *Allow Github Actions to create and approve pull requests*.
. Click Save to apply the settings.

See link:https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions[Configuring the default `GITHUB_TOKEN` permissions] on the Github docs pages for more information.

== Github Actions Workflows
The GitHub Actions workflows within this repository adhere to a standardized approach tailored for the link:https://github.com/sommerfeld-io[Sommerfeld.io Github organization]. These workflows serve as a blueprint, showcasing best practices and a consistent structure that other projects can leverage and adapt. While maintaining this standardized framework, individual projects within the Sommerfeld.io organization might diverge in certain details to accommodate their unique requirements or specific workflows.

This project is equipped with linter definitions, serving as a foundational standard for other repositories within the organization. These linter definitions establish a baseline coding style and quality standard that other projects can adopt and build upon. This serves as a valuable resource for other repositories within the organization, allowing them to maintain a cohesive codebase and adhere to best practices in coding standards.

CAUTION: TODO generate docs fpr github actions workflows and link here

// Development Tools
include::ROOT:partial$/development/architecture.adoc[]
