---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: .devcontainer
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/main/ui/material-admin-pro/ui-bundle/Dockerfile
    schedule:
      interval: weekly
  # - package-ecosystem: npm
  #   directory: src/main/ui/material-admin-pro/ui-bundle
  #   schedule:
  #     interval: weekly
