---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # website
  - package-ecosystem: docker
    directory: website
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: website/ui/template
    schedule:
      interval: weekly
