---
ls:
  .adoc: kebab-case | SCREAMING_SNAKE_CASE | PascalCase
  .md: kebab-case | SCREAMING_SNAKE_CASE
  .puml: kebab-case

  .conf: kebab-case
  .feature: kebab-case
  .go: snake_case
  .json: kebab-case
  .rb: kebab-case
  .sh: kebab-case
  .tf: kebab-case
  .yml: kebab-case
  .yaml: kebab-case

  .css: kebab-case
  .hbs: kebab-case
  .html: kebab-case
  .js: kebab-case
  .svg: kebab-case

  Dockerfile: PascalCase
  Jenkinsfile: PascalCase
  Makefile: PascalCase
  Vagrantfile: PascalCase

  .env: lowercase
  .folderslintrc: lowercase
  .gitignore: lowercase
  .gitkeep: lowercase
  .shellcheckrc: lowercase

  .properties: kebab-case

ignore:
  - .git
  - .idea
  - .vscode
  - node_modules
  - .gitpod.yml
  - target
  - .adoc-links.json
  - .gherkin-lintrc.json
  - .ls-lint.yml
  - .pre-commit-config.yaml
  - .yamllint.yml

  # UI bundle
  - src/main/ui/material-admin-pro/ui-bundle/node_modules
  - src/main/ui/material-admin-pro/ui-bundle/public
  - src/main/ui/material-admin-pro/ui-bundle/.gulp.json
  - src/main/ui/material-admin-pro/ui-bundle/src/js/vendor/highlight.bundle.js
  - src/main/ui/material-admin-pro/ui-bundle/src/js/vendor/bootstrap.bundle.min.js
