---
# @file .pre-commit-config.yml
# @brief Config for pre-commit.
#
# @description Run the defined checks before committing code to the remote repo. This should catch
# simple violations early and lessens the amount of pipeline failures.
#
# Every time you clone a project using pre-commit running ``pre-commit install`` should always be the
# first thing you do.
#
# IMPORTANT: For pre-commit to work, this file must carry the extension ``.yaml``, NOT ``.yml``.
#
# == Install the git hook scripts
#
# run ``pre-commit install`` to set up the git hook scripts. Now pre-commit will run automatically
# on git commit.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      #- id: check-yaml
      - id: check-added-large-files
        exclude: |
            (?x)^(
                website/ui/appstack/template/pages/css/light.css|
                website/ui/appstack/template/pages/css/dark.css|
                website/ui/appstack/template/pages/js/app.js|
                website/ui/appstack/ui-bundle/src/css/light.css|
                website/ui/appstack/ui-bundle/src/css/dark.css|
                website/ui/appstack/ui-bundle/src/js/00-app.js|
                website/ui/appstack/ui-bundle/package-lock.json|
                website/ui/material-admin-pro/template/pages/js/material.js|
                website/ui/material-admin-pro/template/pages/css/styles.css|
                website/ui/material-admin-pro/ui-bundle/src/js/material.js|
                website/ui/material-admin-pro/ui-bundle/src/css/styles.css|
                website/ui/material-admin-pro/material-admin-pro-1.0.6.tar.xz
            )$
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        entry: yamllint
        types: [file, yaml]
  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        language: docker_image
        types: ["dockerfile"]
        entry: hadolint/hadolint hadolint
