= Github Repository Settings

A summary of all settings that are specific to this project.

== Actions Secrets
Create link:https://github.com/organizations/sommerfeld-io/settings/secrets/actions[Github Actions secrets for the organization] to prepare interaction with DockerHub and Google Chat from Github Actions workflows:

[cols="1,3", options="header"]
|===
|Secrets |Description
|`DOCKERHUB_USER` |My DockerHub User
|`DOCKERHUB_TOKEN` |See https://hub.docker.com/settings/security (Access Token Description = "Repo www-sommerfeld-io")
|`GH_TOKEN_REPO_AND_PROJECT` |Bitwarden entry "GH_TOKEN_REPO_AND_PROJECT"
|`GOOGLE_CHAT_WEBHOOK` |Google Chat (Account = sebastian@sommerfeld.io) -> Channel "Workflows: sommerfeld-io" -> Apps & Integrations -> Manage Webhooks
|===

NOTE: Secrets must be specified here because a private repository cannot inherit actions secrets from the organization with my plan.

== Dependabot Secrets
Create link:https://github.com/organizations/sommerfeld-io/settings/secrets/dependabot[Dependabot secrets for the organization] to allow successful Github Actions workflows which are triggered by dependabot (like assigning PRs to a project).

[cols="1,3", options="header"]
|===
|Secrets |Description
|`DOCKERHUB_USER` |Bitwarden entry "DOCKERHUB_USER"
|`DOCKERHUB_TOKEN` |See https://hub.docker.com/settings/security (Access Token Description = "Repo www-sommerfeld-io")
|`GH_TOKEN_REPO_AND_PROJECT` |Bitwarden entry "GH_TOKEN_REPO_AND_PROJECT"
|`GOOGLE_CHAT_WEBHOOK` |Google Chat (Account = sebastian@sommerfeld.io) -> Channel "Workflows: sommerfeld-io" -> Apps & Integrations -> Webhooks
|`SONAR_TOKEN` |Configured when creating the project in SonarCloud (manage Tokens on the link:https://sonarcloud.io/account/security[SonarCloud Security
|===

NOTE: Although dependabot secrets can be inherited from the organization with my plan, these would contain other values than the Actions secrets.
