= Github Organization Settings
Sebastian Sommerfeld <sebastian@sommerfeld.io>

This page lists all configurations for the link:https://github.com/sommerfeld-io[sommerfeld-io Github organization] wich are done manually.

== Organization
link:https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations[Organizations] are shared accounts where businesses and open-source projects can collaborate across many projects at once, with sophisticated security and administrative features.

You can invite an unlimited number of people to join your organization, In addition to managing access to the organization itself, you can separately manage access to your organization's repositories, project boards, and apps. To harden your organization's security, you can enforce security requirements and review the organization's audit log.

All organizations can own an unlimited number of public and private repositories.

Organizations can manage secrets and make them available for the organizations repositories.

=== Discussions
Setting up Discussions for your organization will allow you to broadcast updates, answer questions, and hold conversations for the entire organization.

Discussions cannot be enabled / disabled for each individual repository. Discussions are enabled for all repositories at organization-level (see https://github.com/organizations/sommerfeld-io/settings/discussions).

=== Actions secrets
Create link:https://github.com/organizations/sommerfeld-io/settings/secrets/actions[Github Actions secrets for the organization] to prepare interaction with DockerHub and Google Chat from Github Actions workflows:

[cols="1,3", options="header"]
|===
|Secrets |Description
|`DOCKERHUB_USER` |Bitwarden entry "DOCKERHUB_USER"
|`DOCKERHUB_TOKEN` |See https://hub.docker.com/settings/security (Access Token Description = "Github Organization sommerfeld-io")
|`GH_TOKEN_REPO_AND_PROJECT` |Bitwarden entry "GH_TOKEN_REPO_AND_PROJECT"
|`GOOGLE_CHAT_WEBHOOK` |Google Chat (Account = sebastian@sommerfeld.io) -> Channel "Workflows: sommerfeld-io" -> Apps & Integrations -> Manage Webhooks
|===

CAUTION: TODO: remove this section once all other repos are gone

=== Dependabot secrets
Create link:https://github.com/organizations/sommerfeld-io/settings/secrets/dependabot[Dependabot secrets for the organization] to allow successful Github Actions workflows which are triggered by dependabot (like assigning PRs to a project).

[cols="1,3", options="header"]
|===
|Secrets |Description
|`DOCKERHUB_USER` |Bitwarden entry "DOCKERHUB_USER"
|`DOCKERHUB_TOKEN` |See https://hub.docker.com/settings/security (Access Token Description = "Github Organization sommerfeld-io")
|`GH_TOKEN_REPO_AND_PROJECT` |Bitwarden entry "GH_TOKEN_REPO_AND_PROJECT"
|`GOOGLE_CHAT_WEBHOOK` |Google Chat (Account = sebastian@sommerfeld.io) -> Channel "Workflows: sommerfeld-io" -> Apps & Integrations -> Webhooks
|===

== Configuring the default `GITHUB_TOKEN` permissions
By default, when you create a new repository in your personal account, `GITHUB_TOKEN` only has read access for the `contents` and `packages` scopes. If you create a new repository in an organization, the setting is inherited from what is configured in the organization settings.

. On GitHub.com, navigate to the main page of the repository.
. Under your repository name, click *Settings*. If you cannot see the "Settings" tab, select the dropdown menu, then click *Settings*.
. In the left sidebar, click *Actions*, then click *General*.
. Under "Workflow permissions", choose whether you want the `GITHUB_TOKEN` to have read and write access for all scopes, or just read access for the `contents` and `packages` scopes.
.. For the sommerfeld-io ogranization choose *Read repository contents and packages permissions*.
.. For the sommerfeld-io ogranization check *Allow Github Actions to create and approve pull requests*.
. Click Save to apply the settings.

See link:https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions[Configuring the default `GITHUB_TOKEN` permissions] on the Github docs pages for more information.
