---
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'website-stack'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  ##############################################################################
  #    blackbox exporter                                                       #
  ##############################################################################
  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - website:7888
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  ##############################################################################
  #    apache exporter                                                         #
  ##############################################################################
  - job_name: apache
    scrape_interval: "15s"
    static_configs:
      - targets:
          - apache-exporter:9117
