= Contribute to our Projects
Sebastian Sommerfeld <sebastian@sommerfeld.io>
:page-layout: full-page

We're thrilled that you'd like to contribute to our projects.

== Submitting a pull request
To align with our principles and best practices, we recommend reading xref:ROOT:development/guidelines.adoc[] and xref:ROOT:development/tools.adoc[]. These pages contain information that will help ensure consistency and adherence to our development guidelines and standards.

. Fork and clone the repository
. Create a new branch: `git checkout -b my-branch-name`
. Make your changes and include tests (preferably by using TDD)
. Make sure the tests pass
. Format code and build artifacts
. Push to your fork and submit a pull request
. Pat your self on the back and wait for your pull request to be reviewed and merged

Here are a few things you can do that will increase the likelihood of your pull request being accepted:

. Write tests
. Make sure the documentation (`docs` folder) and any other relevant documentation are kept up-to-date
. We try to follow SemVer v2.0.0 so randomly breaking public APIs is not an option
. Keep your change as focused as possible - If there are multiple changes you would like to make that are not dependent upon each other, consider submitting them as separate pull requests
. Write link:https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[a good commit message]
