= About this UI bundle
Sebastian Sommerfeld <sebastian@sommerfeld.io>

This UI bundle is based on the link:https://startbootstrap.com/theme/material-admin-pro[Material Admin Pro]. To turn this template into an Antora UI bundle, the link:https://gitlab.com/antora/antora-ui-default[Antora Default UI] served as a guideline.

== About the HTML template
The `website/ui/material-admin-pro/template` only contains static HTML, CSS, ... files. For deeper changes, unpack `website/ui/material-admin-pro/material-admin-pro-1.0.6.tar.xz` and update the source files.

Changes could mean updating the sites color scheme. You can use the link:https://startbootstrap.com/previews/material-admin-pro[theme preview on StartBootstrap.com] to generate new colors through the theme customizer.

[code, scss]
----
$primary: #5b84b1; // 91 132 177
$secondary: #9cc3d5; // 156 195 213
$success: #00ac69; // 0 172 105
$danger: #e81500; // 232 21 0
$warning: #f4a100; // 244 161 0
$info: #5b84b1; // 91 132 177
----

The best way to extend and customize the Material Admin Pro theme is to work with the source files contained in the `src` directory. To start, you will need to launch the development environment by installing project dependencies and running a script in your terminal. To do this, follow these simple steps:

To start, you will need to launch the development environment by installing project dependencies and running a script within your terminal. To do this, follow these simple steps:

* Before you begin, make sure your development environment includes Node.js and npm. Download and install Node.js from https://nodejs.org/en/download/ which will install Node.js and npm on your system.
* Unpack `website/ui/material-admin-pro/material-admin-pro-1.0.6.tar.xz`
* Open your terminal, and navigate into the root folder of the theme.
* Install project dependencies by running `npm install`
* Start the project by running `npm start`

With everything installed properly, running the `npm start` script will launch a window in your default web browser showing you a local preview of the Material Admin Pro theme. The script will also watch for changes made to the `.pug`, `.scss`, or `.js` files within the `src` directory, and it will compile and reload the browser when changes are saved.

TIP: See https://docs.startbootstrap.com/material-admin-pro/quickstart for further instructions.

== 3rd-Party Artifacts
* The Github logos shipped with the UI bundle are downloaded from https://github.com/logos (see this page for Githubs terms of use)
* The Docker logos shipped with the UI bundle are downloaded from https://www.docker.com/company/newsroom/media-resources (see this page for Dockers terms of use)
* The Google fonts are shipped as part of the UI bundle, so there are no requests to a Google server from the live website (for Googles terms of use see https://developers.google.com/fonts/terms and the "Can I embed Google Fonts in my website without sending end-user data to Google's servers?" section on https://developers.google.com/fonts/faq/privacy)

== UI Layouts
The most drastic way to change the appearance of the page is to change the HTML. The HTML is controlled by layouts, which are Handlebars templates located in `[.path]_src/layouts`. A layout typically includes partials, located in `[.path]_src/partials`, which are reusable template fragments. Partials may, in turn, include other partials.

This project currently features multiple layouts:

* `default.hbs` -> Default layout for documentation pages
* `full-page.hbs` -> Layout for documentation pages which uses the full width of the page and does not render a Table of Contents.
* `homepage.hbs` -> Layout for the websites start page
* `404.hbs` -> Special layout which acts as the 404 error page

If a page doesn't specify a layout, the `[.path]_default.hbs_` layout is used. To specify a layout, the page file must declare the `page-layout` document attribute in the AsciiDoc header. The value of that attribute should match the stem of the layout file (the filename minus the file extension, e.g., `homepage`).

[source,asciidoc]
----
= Homepage
Sebastian Sommerfeld <sebastian@sommerfeld.io>
:page-layout: homepage
----

In this case, Antora will select the `[.path]_homepage.hbs_` layout for this page instead of `[.path]_default.hbs_`. Using a dedicated layout affords a lot of control over what gets displayed on this page. Every layout has access to the same UI model.
