= Contact

Feel free to contact me via sebastian@sommerfeld.io. 

== Terms
While we strive to keep the information up to date and accurate, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the website or the information, products, services, or related graphics contained on the website. Any reliance you place on such information is therefore strictly at your own risk. In no event will we be liable for any loss or damage, including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website. Through this website, you can visit other websites which are not under our control. We have no control over the nature, content, and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them. Every effort is made to keep the website up and running smoothly. However, we take no responsibility for, and will not be liable for, the website being temporarily unavailable for whatever reason.

All projects / components / repositories comprising www.sommerfeld.io are accompanied by their individual licenses, which are stored within their respective repositories. Even in the absence of a written license, copyright laws apply to protect the intellectual property associated with each project. It is important to respect and comply with the applicable license terms and copyright laws when accessing or using any material from these projects.

== Privacy
This website values your privacy and does not use any cookies. It is a static site generated by Antora, solely serving static content. The search function within the website does not send any data to remote servers. It operates using a statically generated search index, enabling it to function even when offline. Rest assured that your browsing experience on this website remains private and data is not collected or shared.
