= Makefile

Build the website from its source files and run the website within a Docker container.

== Overview

This Makefile streamlines the process of building the website from its
source files and orchestrating its execution within a Docker container.

== How to use this Makefile

The default target, which is triggered when simply using `make` combines `make build`
and `make run`.

=== `make build`

Automates the process of creating a Docker image that encapsulates the entire
link:https://www.sommerfeld.io[sommerfeld-io website] within an Apache httpd web server. The
website is built with Antora first. This target simplifies the setup and configuration required
to run the website locally. The image is based on the official link:https://hub.docker.com/_/httpd[Apache httpd]
image.

Per default, Apache httpd runs as `root` user because only root processes can listen to ports
below 1024. The default http port for web applications is 80. But this means the user inside the
container is `root` which poses a potential security risk. And since the webserver is running
inside a Docker container it is not important what port is used inside the container. So the http
port is changed to 7888 and the user is switched to the already present user `www-data`.

Apache is trying to write a file into `/usr/local/apache2/logs`, but the `www-data` user does
not have permission to create files in this directory. So permissions to this directory are
updated as well.

|===
| Image | Port | Protocol

| `local/website:dev`
| 7888
| http
|===

The image is intended for local testing purposes. For production use, take a look at the
link:https://hub.docker.com/r/sommerfeldio/website[`sommerfeldio/website`] image on
Dockerhub.

=== `make run`

Launches a Docker container based on the newly created image. The container is started in the
foreground. The locally hosted website can be accessed via a web browser at http://localhost:7888.

=== `make build-ui`

Automates the process of building the Antora UI bundle. Use this target from a Github Actions
workflow to build the UI bundle from a pipeline. This target does not start up a webserver to
preview the UI bundle in a browser.

=== `make preview-ui`

Run a local preview of the documentation site using the UI bundle. The preview uses demo
content from the `preview-src` folder for testing and development purposes. The UI bundle
preview is available through http://localhost:5252. This target uses `make build-ui`
as a prerequisites.

=== `make preview-template`

Exposes the HTML template through a webserver on http://localhost:5353.

=== `make clean`

Remove the local Docker image

=== `make all`

This phony target triggers all build-related targets (`make build-ui` and `make build`)

== Prerequisites

This Makefile needs Node, NPM and Gulp installed. To avoid having to install all
prerequisites on your host, open the project in the devcontainer from this repo. Python3
is needed as well. The xref:AUTO-GENERATED:-devcontainer/Dockerfile.adoc[DevContainer]
for this repository ships all these depencencies.
