= Makefile

Build the website from its source files and run the website within a Docker container.

== Overview

This Makefile streamlines the process of building the website from its
source files and orchestrating its execution within a Docker container.

== Build an run the website

The `build` target automates the process of creating a Docker image thatencapsulates
the entire link:https://www.sommerfeld.io[sommerfeld-io website] within an Apache httpd
web server. The website is built with Antora first. This target simplifies the setup and
configuration required to run the website locally. The image is based on the official
link:https://hub.docker.com/_/httpd[Apache httpd] image.

[source, bash]

----
make build
----

The `run` target launches a Docker container based on the newly created image. The container
is started in the foreground. The locally hosted website can be accessed via a web browser at
http://localhost:7888.

[source, bash]

----
make run
----

Per default, Apache httpd runs as `root` user because only root processes can listen to ports
below 1024. The default http port for web applications is 80. But this means the user inside the
container is `root` which poses a potential security risk. And since the webserver is running
inside a Docker container it is not important what port is used inside the container. So the http
port is changed to 7888 and the user is switched to the already present user `www-data`.

Apache is trying to write a file into `/usr/local/apache2/logs`, but the `www-data` user does
not have permission to create files in this directory. So permissions to this directory are
updated as well.

|===
| What | Port | Protocol

| `local/website:dev`
| 7888
| http
|===

The image is intended for local testing purposes. For production use, take a look at the
link:https://hub.docker.com/r/sommerfeldio/website[`sommerfeldio/website`]  image on
Dockerhub.

== Remove the Docker image

To remove the local Docker image, just use `make remove-image`

== HTML Template

To expose the HTML template through a webserver, just use `make template`. The HTML
template is available through http://localhost:5353.

[source, bash]

----
make template
----

== Build and preview UI Bundle

The `ui-bundle` target automates the process of building the Antora UI
bundle, running a local preview of the documentation site, and using demo
content from the `preview-src` folder for testing and development purposes.

[source, bash]

----
make ui
----

The UI bundle preview is available through http://localhost:5252.

NOTE: To build the UI bundle from a Github Actions workflow, use  `make build-ui`.
This target does not start up a webserver to preview the UI bundle in a browser.

This target needs Node, NPM and Gulp installed. To avoid having to install
all prerequisites on your host, open the project in the devcontainer from
this repo.
