Website configuration and landingpage contents for www.sommerfeld.io.

image:{github-actions-url}/{job-generate-docs}/{badge}[Github Badge, link={github-actions-url}/{job-generate-docs}]
image:{github-actions-url}/{job-ci}/{badge}[Github Badge, link={github-actions-url}/{job-ci}]
image:{github-actions-url}/{job-release}/{badge}[Github Badge, link={github-actions-url}/{job-release}]

* Github Repository -> {url-project}
* Where to file issues -> {url-project}/issues

== About this project
The Docker image "sommerfeldio/website" represents the complete website from https://www.sommerfeld.io[www.sommerfeld.io]. The image is hosted on link:https://hub.docker.com/r/sommerfeldio/website[Docker Hub]. This image encapsulates all the necessary components, including HTML, CSS, JavaScript, and other resources, required to run the sommerfeld.io website (locally or in a production environment) within a Docker container.

== How to use this project
[source,bash]
----
docker run --rm -it -p 7888:80 sommerfeldio/website:latest
----

== About the tags and versions
This Docker image follows a tagging convention based on semantic versioning to distinguish between stable and unstable releases. Each stable version of the image is tagged with a specific semantic version (e.g. `:v0.1.2`), while the `:latest` tag always points to the most recent stable version.

Versions with a `-SNAPSHOT` suffix (e.g. `:v0.1.2-SNAPSHOT`) indicate unstable releases, usually used for testing or development purposes. These versions are not recommended for production use. `:latest` never points to a Snapshot release.

The image may have a `:ci` tag, which represents an unstable nightly build. These versions come from CI-builds and/or nightly builds and are useful for continuous integration and testing purposes. The `:ci` tag is not meant for production use and may contain experimental features or unresolved issues.

== Risks and Technical Debts
link:{url-project}/issues?q=is%3Aissue+label%3Asecurity%2Crisk+is%3Aopen[All issus labeled as `risk` (= some sort of risk or a technical debt) or `security` (= related to security issues)] are tracked as Github issues and carry the respective label.

== Contact
Feel free to contact me via sebastian@sommerfeld.io or visit my website https://www.sommerfeld.io.
