---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: website-access-log
    static_configs:
      - targets:
          - localhost
        labels:
          job: website-access-log
          __path__: /var/log/website-access.log
  - job_name: website-error-log
    static_configs:
      - targets:
          - localhost
        labels:
          job: website-error-log
          __path__: /var/log/website-error.log
