Website configuration for link:https://www.sommerfeld.io[www.sommerfeld.io] as well as the Antora ui bundle.

image:{github-actions-url}/{job-generate-docs}/{badge}[Github Badge, link={github-actions-url}/{job-generate-docs}]
image:{github-actions-url}/{job-ci}/{badge}[Github Badge, link={github-actions-url}/{job-ci}]
image:{github-actions-url}/{job-release}/{badge}[Github Badge, link={github-actions-url}/{job-release}]

== About this project
The Docker image `link:https://hub.docker.com/r/sommerfeldio/website[sommerfeldio/website]` represents the complete website from https://www.sommerfeld.io[www.sommerfeld.io]. The image is hosted on DockerHub. This image encapsulates all necessary components including the UI bundle required to run the link:http://www.sommerfeld.io[www.sommerfeld.io website] within a Docker container (locally or in a production environment).

* Github Repository -> {url-project}
* Where to file issues -> {url-project}/issues
* Container Registry -> https://hub.docker.com/r/sommerfeldio/{project-name}
* Sonar -> https://sonarcloud.io/project/overview?id=sommerfeld-io_{project-name}

== How to use this project
This project is exclusively available as a Docker image, meaning that it is packaged and distributed as a containerized application using Docker technology. There is no traditional FTP-based upload to any web space.

[source,bash]
----
docker run --rm -it -p 7888:7888 sommerfeldio/website:latest
----

== About the tags and versions
See https://github.com/sommerfeld-io/dev-environment-config/blob/main/docs/modules/ROOT/partials/docker-tag-strategy.adoc

== Webserver inside the Docker image
All pages are served from an Apache webserver. This webserver comes with some configurations specific to this project.

. To avoid running the image as `root`, the permissions of `/usr/local/apache2/logs` are changed to allow `www-data` to write logs. Additionally the default http port is changed to `7888`, so keep that in mind when mapping ports in a `docker run ...` command. This way the image can be used without root permissions because the httpd server inside the container is started with the already existing user `www-data`.
. The UI bundle links to some static pages like the contact page or the terms of use. To avoid complex URLs inside the UI bundle and to enhance flexibility, the `httpd.conf` features some link:https://httpd.apache.org/docs/2.2/mod/mod_rewrite.html[rewrite rules] for these pages.

=== Apache Status
The webserver exposes its status information as http://localhost:7888/server-status.

== UI Bundle
This project also contains the Antora UI bundle sources. This UI bundle represents the design for all Antora-based pages of https://www.sommerfeld.io[www.sommerfeld.io].

NOTE: Please note that despite the availability of released versions, this UI bundle is still considered a prototype which means it is not recommended for production use and might still undergo significant changes.

To build the UI bundle, make use of `xref:AUTO-GENERATED:build-and-run-website-sh.adoc[]` or `xref:AUTO-GENERATED:build-and-preview-ui-bundle-sh.adoc[]`.

If you want to simply use the UI for an Antora-generated site, add the following UI configuration to your playbook:
[source, yaml]
----
ui:
  bundle:
    url: https://github.com/sommerfeld-io/website/releases/download/v0.2.0-alpha.1/ui-bundle-0.2.0-alpha.1.zip
    snapshot: true
----

The `snapshot` flag tells Antora to fetch the UI when the `--fetch` command-line flag is present. This setting is required because updates to the UI bundle are pushed to the same URL. If the URL were to be unique, this setting would not be required.

== Risks and Technical Debts
link:{url-project}/issues?q=is%3Aissue+label%3Asecurity%2Crisk+is%3Aopen[All issues labeled as `risk` (= some sort of risk or a technical debt) or `security` (= related to security issues)] are tracked as Github issues and carry the respective label.

== Contact
Feel free to contact me via sebastian@sommerfeld.io or visit my website https://www.sommerfeld.io.
