Website configuration for link:https://www.sommerfeld.io[www.sommerfeld.io] as well as the Antora ui bundle.

image:{github-actions-url}/{job-generate-docs}/{badge}[Github Badge, link={github-actions-url}/{job-generate-docs}]
image:{github-actions-url}/{job-lint}/{badge}[Github Badge, link={github-actions-url}/{job-lint}]
image:{github-actions-url}/{job-build}/{badge}[Github Badge, link={github-actions-url}/{job-build}]

== About this module
The Docker image `link:https://hub.docker.com/r/sommerfeldio/website[sommerfeldio/website]` represents the complete website link:from https://www.sommerfeld.io[www.sommerfeld.io]. The image is hosted on DockerHub. This image encapsulates all necessary components including the UI bundle required to run the link:http://www.sommerfeld.io[www.sommerfeld.io website] within a Docker container (locally or in a test or production environment).

* Github Repository -> {url-project}
* Where to file issues -> {url-project}/issues
* Container Registry -> https://hub.docker.com/r/sommerfeldio/{project-name}
* Sonar -> https://sonarcloud.io/project/overview?id=sommerfeld-io_{project-name}

== How to use this module
This project is exclusively available as a Docker image, meaning that it is packaged and distributed as a containerized application using Docker technology. There is no traditional FTP-based upload to any web space.

[source,bash]
----
docker run --rm -it -p 7888:7888 sommerfeldio/website:latest
----

== About the tags and versions
See https://github.com/sommerfeld-io/dev-environment-config/blob/main/docs/modules/ROOT/partials/docker-tag-strategy.adoc

== Webserver inside the Docker image
All pages are served from an Apache webserver. This webserver comes with some configurations specific to this project.

. To avoid running the image as `root`, the permissions of `/usr/local/apache2/logs` are changed to allow `www-data` to write logs. Additionally the default http port is changed to `7888`, so keep that in mind when mapping ports in a `docker run ...` command. This way the image can be used without root permissions because the httpd server inside the container is started with the already existing user `www-data`.
. The UI bundle links to some static pages like the contact page or the terms of use. To avoid complex URLs inside the UI bundle and to enhance flexibility, the `httpd.conf` features some link:https://httpd.apache.org/docs/2.2/mod/mod_rewrite.html[rewrite rules] for these pages.

=== Apache Status
The webserver exposes its status information as http://localhost:7888/server-status.

== UI Bundle
This project also contains the Antora UI bundle sources. This UI bundle represents the design for all Antora-based pages of https://www.sommerfeld.io[www.sommerfeld.io].

The UI bundle is built alongside the whole website ensuring that the latest UI bundle is used for www.sommerfeld.io. This way there is no need to publish the UI bundle anywhere because it is part of the Docker image which serves the website.

== Risks and Technical Debts
link:{url-project}/issues?q=is%3Aissue+label%3Asecurity%2Crisk+is%3Aopen[All issues labeled as `risk` (= some sort of risk or a technical debt) or `security` (= related to security issues)] are tracked as Github issues and carry the respective label.

== Contact
Feel free to contact me via sebastian@sommerfeld.io or visit my website https://www.sommerfeld.io.
