---
site:
  title: Sommerfeld.io
  url: /
  start_page: website::index.adoc
  robots: allow

content:
  branches: ['*', '!dependabot/*']
  # tags: [v*]
  sources:
    - url: https://github.com/sommerfeld-io/dev-environment-config.git
      start_path: docs
    - url: https://github.com/sommerfeld-io/infrastructure-config.git
      start_path: docs
    - url: https://github.com/sommerfeld-io/website.git
      start_path: docs

asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  clean: true
  dir: /tmp/antora/website/public

runtime:
  cache_dir: /tmp/antora/website/cache/antora
  fetch: true
