---
site:
  title: Sommerfeld.io
  url: /
  start_page: website::index.adoc
  robots: allow

content:
  branches: ['*', '!dependabot/*']
  # tags: [v*]
  sources:
    - url: https://github.com/sommerfeld-io/dev-environment-config.git
      start_path: docs
    - url: https://github.com/sommerfeld-io/infrastructure-config.git
      start_path: docs
    - url: https://github.com/sommerfeld-io/website.git
      start_path: docs
    - url: https://github.com/sommerfeld-io/website-ui-bundle.git
      start_path: docs

asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki

antora:
  extensions:
    - require: '@antora/lunr-extension'
      enabled: true
      index_latest_only: true
      snippet_length: 160

ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/sommerfeld-io/website-ui-bundle/releases/download/v0.1.4-SNAPSHOT/ui-bundle-0.1.4-SNAPSHOT.zip
    #   url: http://docker-host-gateway:5252/ui-bundle.zip
    snapshot: true

output:
  clean: true
  dir: /tmp/antora/website/public

runtime:
  cache_dir: /tmp/antora/website/cache/antora
  fetch: true
