---
# @file build.yml
# @brief Github Actions workflow for the website module that builds the app and runs automated tests.
#
# @description This GitHub Actions workflow for the website module is designed for integration and
# automates essential tasks such as code linting, building the application, and running automated
# tests. It ensures code quality, catches errors early, and provides developers with quick feedback
# on their changes. The workflow triggers automatically when new code is pushed to the remote repo
# and automatically each night, making it an integral part of the development process to maintain
# a stable and reliable codebase.


name: Build (is releasable)

on:
  push:
    branches:
      - main
    # branches-ignore:
    #   - dependabot/**
  pull_request:
    branches-ignore:
      - dependabot/**
  schedule:
    - cron: '0 3 * * 1' # https://crontab.guru/#0_2_*_*_1

env:
  REGISTRY: docker.io
  IMAGE: sommerfeldio/website
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

permissions:
  contents: read

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run yamllint
        run: make lint-yaml
        shell: bash

  lint-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run folderslint in container
        run: make lint-folders
        shell: bash

  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ls-lint in container
        run: make lint-filenames
        shell: bash

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: node_modules target

  lint-makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run checkmake in container
        run: make lint-makefile
        shell: bash

  validate-inspec-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate inspec profile
        run: make validate-inspec
        shell: bash

  ui-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/main/ui/material-admin-pro/ui-bundle/Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker image build
        uses: docker/build-push-action@v5
        with:
          context: src/main/ui/material-admin-pro/ui-bundle
          platforms: linux/amd64
          push: false
          tags: local/ui-preview:dev

  website:
    runs-on: ubuntu-latest
    needs: ['lint-yaml', 'lint-folders', 'lint-filenames', 'shellcheck', 'lint-makefile', 'validate-inspec-profile']
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install gulp-cli
        run: npm install --location=global gulp-cli@2.3.0
        shell: bash
      - name: Build UI bundle
        run: make src/main/ui/material-admin-pro/ui-bundle/build/ui-bundle.zip
        shell: bash
      - name: Set docker tag
        id: vars
        run: |
          echo "Ref = ${{ github.ref }}"
          echo "Ref Name = $GITHUB_REF_NAME"
          echo "Head Ref = $GITHUB_HEAD_REF"

          # TAG="$GITHUB_REF_NAME"
          # if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          #   TAG="$GITHUB_HEAD_REF"
          # fi

          TAG='rc'

          echo "tag = $TAG"
          echo "DOCKER_TAG=$TAG" >> $GITHUB_OUTPUT
        shell: bash
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
      - name: Docker image build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
          tags: ${{ env.IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true
      - name: Docker Scout Compare
        uses: docker/scout-action@v1.3.0
        with:
          command: compare
          image: ${{ env.IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }}
          to: ${{ env.IMAGE }}:latest
          exit-code: false
          write-comment: ${{ github.event_name == 'pull_request' }}
      - name: Docker Scout CVEs
        uses: docker/scout-action@v1.3.0
        with:
          command: cves
          image: ${{ env.IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }}
          # exit-code: ${{ github.event_name == 'pull_request' }}
          exit-code: false
          write-comment: ${{ github.event_name == 'pull_request' }}

  inspec-tests:
    runs-on: ubuntu-latest
    if: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
    needs: ['website']
    strategy:
      matrix:
        inspec-profile: ['website']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set docker tag
        id: vars
        run: |
          echo "Ref = ${{ github.ref }}"
          echo "Ref Name = $GITHUB_REF_NAME"
          echo "Head Ref = $GITHUB_HEAD_REF"

          # TAG="$GITHUB_REF_NAME"
          # if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          #   TAG="$GITHUB_HEAD_REF"
          # fi

          TAG='rc'

          echo "tag = $TAG"
          echo "DOCKER_TAG=$TAG" >> $GITHUB_OUTPUT
        shell: bash
      - name: Pull ${{ env.IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }} container
        run: docker pull ${{ env.IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }}
        shell: bash
      - name: Start ${{ env.IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }} container
        run: docker run --rm --name ${{ matrix.inspec-profile }} -d -p 7888:7888 ${{ env.IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }}
        shell: bash
      - name: Run Inspec tests
        run: |
          sleep 5s
          docker run --rm \
            --volume /var/run/docker.sock:/var/run/docker.sock  \
            --volume ./src/test/inspec:/inspec \
            --workdir /inspec \
            chef/inspec:5.22.36 exec ${{ matrix.inspec-profile }} --target docker://${{ matrix.inspec-profile }} --chef-license=accept-no-persist
        shell: bash
      - name: Stop ${{ env.IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }} container
        if: always()
        run: docker stop ${{ matrix.inspec-profile }}
        shell: bash

  on-failure:
    runs-on: ubuntu-latest
    needs: ['sonar-scan', 'lint-yaml', 'lint-folders', 'lint-filenames', 'shellcheck', 'lint-makefile', 'validate-inspec-profile', 'ui-preview', 'website', 'inspec-tests']
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
