---
name: Generate Docs (as Code)

on:
  push:
    # branches: [ "main", "feat/*", "release/*" ]
    branches-ignore:
      - dependabot/**

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print Branchname
        run: echo ${{github.ref}}
      - name: Adjust version in antora.yml
        uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
        with:
          git_ref: ${{github.ref}}
      - name: Run yamllint for docs/antora.yml
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: docs/antora.yml
      - name: README.adoc
        uses: sebastian-sommerfeld-io/github-action-generate-readme@main
        with:
          caption: Website
      - name: Generate docs from bash scripts
        uses: sebastian-sommerfeld-io/github-action-generate-docs@main
      - name: Generate content (link personal projects from github using the github cli)
        run: |
          JQ_QUERY='.[] | "[.menu-item-name]#link:/_personal-projects/" + .name + "/main[" + .name + "]#" + " [.menu-item-desc]#" + .description + "#"'
          TARGET_ADOC="docs/modules/ROOT/partials/AUTO-GENERATED/projects/personal.adoc"

          echo "[INFO] Read personal project from sebastian-sommerfeld-io and write to adoc"
          # gh repo list --visibility=public --no-archived --json=name,description --jq="$JQ_QUERY" > "$TARGET_ADOC"
          gh api users/sebastian-sommerfeld-io/repos --jq="$JQ_QUERY" > "$TARGET_ADOC"

          echo "[INFO] Show $TARGET_ADOC"
          cat "$TARGET_ADOC"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] docs: auto-generated docs"

  validate-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: generate-docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install asciidoc-linwir könnenk-check
        run: npm install --location=global asciidoc-link-check@1.0.15
      - name: Validate links in all adoc files
        run: find . -name '*.adoc' -exec asciidoc-link-check -c .adoc-links.json -p {} \;

  qodana-analysis:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: generate-docs
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download dependencies
        run: |
          files=(
            "analyze.sh"
            "Dockerfile"
            "qodana.yaml"
          )
          for f in "${files[@]}"
          do
            echo "[INFO] Download $f"
            curl "https://raw.githubusercontent.com/sommerfeld-io/dev-environment-config/main/src/main/github-actions/workflows/docs-as-code/$f" --output "$f"
          done
        shell: bash
      - name: Run Qodana
        run: |
          chmod +x analyze.sh
          ./analyze.sh --save-report
        shell: bash
      - name: Upload qodana result to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: target/qodana/report/results/qodana.sarif.json

  on-failure:
    runs-on: ubuntu-latest
    needs: ['generate-docs', 'validate-links', 'qodana-analysis']
    if: failure()

    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
