---
# @file scan.yml
# @brief Github Actions workflow to scan Docker images and the whole project with SonarCloud.
#
# @description This GitHub Actions workflow orchestrates two essential tasks: firstly,
# it employs Docker Scout to scan Docker images, meticulously checking for vulnerabilities
# and outdated components within these images. Secondly, the workflow integrates SonarCloud
# to conduct a comprehensive scan of the entire project's codebase, scrutinizing for code
# quality issues, bugs, security vulnerabilities, and adherence to best practices. By
# combining Docker image analysis and codebase scanning, this workflow ensures a robust
# approach to identifying and addressing potential security flaws and code quality concerns
# within the project, all streamlined within the GitHub Actions automation pipeline.


name: Scan

on:
  push:
    branches:
      - main
    # branches-ignore:
    #   - dependabot/**
  pull_request:
    branches-ignore:
      - dependabot/**
  schedule:
    - cron: '0 3 * * 1' # https://crontab.guru/#0_2_*_*_1

concurrency:
  group: "scan-${{ github.event.repository.name }}-${{ github.ref }}"
  cancel-in-progress: true

# env:
#   REGISTRY: docker.io
#   IMAGE: sommerfeldio/website
#   SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

permissions:
  contents: read

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  on-failure:
    runs-on: ubuntu-latest
    needs: ['sonar-scan']
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
